
#ifndef BLE_API_H_
#define BLE_API_H_

#include "ble/BLE.h"
#include "ble/blecommon.h"
#include "ble/BLEInstanceBase.h"
#include "ble/BLEProtocol.h"
#include "ble/CallChainOfFunctionPointersWithContext.h"
#include "ble/CharacteristicDescriptorDiscovery.h"
#include "ble/deprecate.h"
#include "ble/DiscoveredCharacteristic.h"
#include "ble/DiscoveredCharacteristicDescriptor.h"
#include "ble/DiscoveredService.h"
#include "ble/FunctionPointerWithContext.h"
#include "ble/Gap.h"
#include "ble/GapAdvertisingData.h"
#include "ble/GapAdvertisingParams.h"
#include "ble/GapEvents.h"
#include "ble/GapScanningParams.h"
#include "ble/GattAttribute.h"
#include "ble/GattCallbackParamTypes.h"
#include "ble/GattCharacteristic.h"
#include "ble/GattClient.h"
#include "ble/GattServer.h"
#include "ble/GattServerEvents.h"
#include "ble/GattService.h"
#include "ble/SafeBool.h"
#include "ble/SecurityManager.h"
#include "ble/ServiceDiscovery.h"
#include "ble/UUID.h"

#include "BatteryService.h"
#include "DeviceInformationService.h"
#include "DFUService.h"
#include "EddystoneConfigService.h"
#include "EddystoneService.h"
#include "HealthThermometerService.h"
#include "EnvironmentalService.h"
#include "HealthThermometerService.h"
#include "HeartRateService.h"
#include "iBeacon.h"
#include "LinkLossService.h"
#include "UARTService.h"
#include "URIBeaconConfigService.h"

#include "nRF51822_API.h"

#endif

